import fs from 'fs'
import path from 'path'
import os from 'os'
import { SUPERROUTER_DIR } from './store'

const HOOK_PATH = path.join(SUPERROUTER_DIR, 'hook.sh')
const SETTINGS_PATH = path.join(os.homedir(), '.claude', 'settings.json')
const HOOK_COMMAND = `bash "${HOOK_PATH}"`

export function generateHookScript(): string {
  // Written as a bash script that invokes python3 for JSON handling.
  // The hook reads the prompt from stdin (UserPromptSubmit hook format),
  // matches against group keywords, and injects routing guidance via stdout.
  //
  // Output format note: Claude Code UserPromptSubmit hooks can inject a
  // system reminder by outputting JSON: {"type":"system_reminder","message":"..."}.
  // If this format changes in future Claude Code versions, update this script.
  return `#!/usr/bin/env python3
# LSM SuperRouter — UserPromptSubmit hook
# Keyword-matches the incoming prompt against routing groups and injects
# relevant skill routing context (up to 3 groups per prompt).
# Auto-generated by Local Skill Manager. Do not edit manually.

import json, os, sys

GROUPS_FILE = os.path.join(os.path.expanduser('~'), '.local-skill-manager', 'superrouter', 'groups.json')
GROUPS_DIR = os.path.join(os.path.expanduser('~'), '.local-skill-manager', 'superrouter', 'groups')

def main():
    if not os.path.exists(GROUPS_FILE):
        return

    raw = sys.stdin.read()
    if not raw.strip():
        return

    hook_input = json.loads(raw)
    prompt = hook_input.get('prompt', '').lower()

    state = json.loads(open(GROUPS_FILE).read())
    if not state.get('globalEnabled'):
        return

    matches = []
    for group in state.get('groups', []):
        if not group.get('enabled'):
            continue
        if len(matches) >= 3:
            break
        keywords = group.get('keywords', [])
        if any(kw.lower() in prompt for kw in keywords):
            gfile = os.path.join(GROUPS_DIR, group['id'] + '.md')
            if os.path.exists(gfile):
                matches.append(open(gfile).read())

    if not matches:
        return

    content = '\\n\\n---\\n\\n'.join(matches)
    print(json.dumps({
        'type': 'system_reminder',
        'message': f'[SuperRouter] Relevant skill routing for this task:\\n\\n{content}'
    }))

try:
    main()
except Exception:
    pass  # silent fail — never block the user
`
}

export function writeHookScript(): void {
  fs.mkdirSync(SUPERROUTER_DIR, { recursive: true })
  fs.writeFileSync(HOOK_PATH, generateHookScript(), 'utf-8')
  fs.chmodSync(HOOK_PATH, 0o755)
}

export function installHook(): void {
  writeHookScript()

  const raw = fs.existsSync(SETTINGS_PATH) ? fs.readFileSync(SETTINGS_PATH, 'utf-8') : '{}'
  const settings = JSON.parse(raw) as Record<string, unknown>

  // Backup settings.json on first LSM write
  const backupPath = SETTINGS_PATH + '.lsm-backup'
  if (!fs.existsSync(backupPath)) {
    fs.writeFileSync(backupPath, raw, 'utf-8')
  }

  if (!settings['hooks']) settings['hooks'] = {}
  const hooks = settings['hooks'] as Record<string, unknown[]>
  if (!hooks['UserPromptSubmit']) hooks['UserPromptSubmit'] = []

  const already = (hooks['UserPromptSubmit'] as Array<{ hooks?: Array<{ command?: string }> }>).some(
    entry => entry.hooks?.some(h => h.command === HOOK_COMMAND),
  )
  if (!already) {
    hooks['UserPromptSubmit'].push({ hooks: [{ type: 'command', command: HOOK_COMMAND }] })
  }

  const tmp = SETTINGS_PATH + '.tmp'
  fs.writeFileSync(tmp, JSON.stringify(settings, null, 2), 'utf-8')
  fs.renameSync(tmp, SETTINGS_PATH)
}

export function uninstallHook(): void {
  if (!fs.existsSync(SETTINGS_PATH)) return
  const settings = JSON.parse(fs.readFileSync(SETTINGS_PATH, 'utf-8')) as Record<string, unknown>
  const hooks = settings['hooks'] as Record<string, unknown[]> | undefined
  if (!hooks?.['UserPromptSubmit']) return

  hooks['UserPromptSubmit'] = (hooks['UserPromptSubmit'] as Array<{ hooks?: Array<{ command?: string }> }>).filter(
    entry => !entry.hooks?.some(h => h.command === HOOK_COMMAND),
  )
  if ((hooks['UserPromptSubmit'] as unknown[]).length === 0) {
    delete hooks['UserPromptSubmit']
  }

  const tmp = SETTINGS_PATH + '.tmp'
  fs.writeFileSync(tmp, JSON.stringify(settings, null, 2), 'utf-8')
  fs.renameSync(tmp, SETTINGS_PATH)
}

export function isHookInstalled(): boolean {
  if (!fs.existsSync(SETTINGS_PATH)) return false
  try {
    const settings = JSON.parse(fs.readFileSync(SETTINGS_PATH, 'utf-8')) as Record<string, unknown>
    const hooks = settings['hooks'] as Record<string, unknown[]> | undefined
    return (hooks?.['UserPromptSubmit'] as Array<{ hooks?: Array<{ command?: string }> }> | undefined)?.some(
      entry => entry.hooks?.some(h => h.command === HOOK_COMMAND),
    ) ?? false
  } catch {
    return false
  }
}
